version: "3"
services:
  apache:
    build:
      context: '.'
      dockerfile: 'Dockerfile-${PHP_VERSION}'
      args:
        - 'SERVER_ROOT=${SERVER_ROOT}'
        - 'PHP_VERSION=${PHP_VERSION}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}'
        - 'XDEBUG=${XDEBUG}'
        - 'INSTALL_ADDITIONAL_EXTENSIONS=${INSTALL_ADDITIONAL_EXTENSIONS}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_APACHE}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${APACHE_HOST_HTTP_PORT}:80'
volumes: {}